image: alpine:latest

variables:
  VERSION: 1.0.0

stages:
  - validation
  - create_tag

shellcheck:
  stage: validation
  before_script:
    - apk add shellcheck
    - shellcheck --version
  script:
    - shellcheck ./*.sh

pylint:
  stage: validation
  script:
    - apk add --update --no-cache python3
    - ln -sf python3 /usr/bin/python
    - ln -sf pip3 /usr/bin/pip
    - python -m ensurepip
    - pip install --no-cache --upgrade pip setuptools
    - pip install selenium==3.141.0
    - pip install requests
    - pip install pylint
    - pylint --version
    - pylint scripts/*.py

release:
  when: manual
  stage: create_tag
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script: echo Releasing latest tag...
  variables:
    tag_name: $VERSION
    description: ./CHANGELOG.md
  only:
    - master
