image: alpine:latest

variables:
  VERSION: 1.0.2

stages:
  - validation
  - create_tag

shellcheck:
  stage: validation
  before_script:
    - apk add shellcheck
    - shellcheck --version
  script:
    - shellcheck ./bin/*.sh

pylint:
  stage: validation
  script:
    - apk add --update --no-cache python3-dev gcc libc-dev libffi-dev
    - ln -sf python3 /usr/bin/python
    - ln -sf pip3 /usr/bin/pip
    - python -m ensurepip
    - python -m pip install --no-cache --upgrade pip setuptools selenium pylint
    - python -m pylint --version
    - PYTHONPATH=${PYTHONPATH}:$(dirname %d) python -m pylint ./src

release:
  when: manual
  stage: create_tag
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script: echo Releasing latest tag...
  variables:
    tag_name: $VERSION
    description: ./CHANGELOG.md
  only:
    - master
