image: alpine:latest

stages:
  - lint

shellcheck:
  stage: lint
  before_script:
    - apk add shellcheck
    - shellcheck --version
  script:
    - shellcheck *.sh

pylint:
  stage: lint
  script:
    - apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
    - python3 -m ensurepip
    - pip3 install --no-cache --upgrade pip setuptools
    - pip install selenium
    - pip install pylint
    - pylint *.py