name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: shellcheck
        id: shellcheck
        run: |
          apt update && apt install -y shellcheck
          shellcheck --version
          shellcheck *.sh
